version: "3"

services:
  nodeapp:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: nodeapp
    container_name: nodeapp
    restart: unless-stopped
    volumes:
      - ./node:/usr/src/app
    ports: 
      - "3000:3000"
    networks: 
      - netapp
    depends_on: 
       - data
  
  data:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: data
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_ROOT_HOST=%
    networks: 
      - netapp
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 8080:80
    networks: 
      - netapp
    depends_on: 
      - nodeapp

networks: 
  netapp:
    driver: bridge